# Generated by Django 2.2.5 on 2019-09-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
                ('food_type', models.CharField(max_length=30)),
                ('food_isspicy', models.CharField(max_length=30)),
                ('food_isprice', models.CharField(max_length=30)),
                ('food_issoup', models.CharField(max_length=30)),
                ('food_isfast', models.CharField(max_length=30)),
                ('food_ismeat', models.CharField(max_length=30)),
                ('food_isrice', models.CharField(max_length=30)),
                ('food_ishot', models.CharField(max_length=30)),
                ('food_isheavy', models.CharField(max_length=30)),
            ],
        ),
    ]
